#!/usr/bin/bash

if [ -f "${KURA_DIR}/user/security/httpskeystore.ks" ]; then
    echo "Keystore already exists"
else
    keytool -genkey -alias localhost -keyalg RSA -keysize 2048 -keystore ${KURA_DIR}/user/security/httpskeystore.ks \
    -deststoretype pkcs12 -dname "CN=Kura, OU=Kura, O=Eclipse Foundation, L=Ottawa, S=Ontario, C=CA" \
    -ext ku=digitalSignature,nonRepudiation,keyEncipherment,dataEncipherment,keyAgreement,keyCertSign \
    -ext eku=serverAuth,clientAuth,codeSigning,timeStamping 
    -ext "SAN=DNS:localhost"
    \-validity 1000 -storepass changeit -keypass changeit
fi

eval exec ${KURA_DIR}/start_kura_debug.sh
